USE MASTER
GO
CREATE DATABASE QLSVNhom
GO
USE QLSVNhom
GO

-- Bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP NVARCHAR(200),
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL
);

-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL,
    PUBKEY VARCHAR(20) NOT NULL
);

-- Bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR(20) PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT
);

-- Bảng LOP
CREATE TABLE LOP (
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20),
);

-- Bảng BANGDIEM
CREATE TABLE BANGDIEM (
    MASV VARCHAR(20),
    MAHP VARCHAR(20),
    DIEMTHI VARBINARY(MAX),
    PRIMARY KEY (MASV, MAHP)
);

GO

-- LOP -> NHANVIEN (MANV)
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

-- LOP -> SINHVIEN (MASV)
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_SINHVIEN
FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

-- LOP -> HOCPHAN (MAHP)
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_HOCPHAN
FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);

-- BANGDIEM -> SINHVIEN (MASV)
ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN
FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

-- BANGDIEM -> HOCPHAN (MAHP)
ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN
FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);