USE QLSVNhom

GO
/* 
	SELECT * FROM SYS.procedures

	DROP PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
	DROP PROCEDURE SP_SIGN_IN_ENCRYPT_NHANVIEN
	DROP PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN

	DROP PROCEDURE SP_INS_PUBLIC_ENCRYPT_SINHVIEN

	DROP PROCEDURE SP_UPDATE_ENCRYPT_DIEM_BY_SINHVIEN_AND_HOCPHAN
	DROP PROCEDURE SP_INS_ENCRYPT_DIEM_BY_SINHVIEN_AND_HOCPHAN
	DROP PROCEDURE SP_GET_ALL_ENCRYPT_HOCPHAN_WITH_DIEM_BY_SINHVIEN
	
	DROP PROCEDURE SP_SEL_PUBLIC_SINHVIEN_BY_NHANVIEN
	DROP PROCEDURE SP_GET_ALL_LOP
	DROP PROCEDURE SP_INS_LOP
	DROP PROCEDURE SP_INS_HOCPHAN
*/
GO

CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG VARBINARY(MAX),
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX),
	@PUB VARCHAR(20)
AS
BEGIN
	INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
	VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @MANV)
END

GO

CREATE PROCEDURE SP_SIGN_IN_ENCRYPT_NHANVIEN
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX)
AS
BEGIN
	IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDN = @TENDN AND MATKHAU = @MK)
	BEGIN
		SELECT 0
		RETURN
	END

	SELECT 1
	RETURN
END

GO

CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX)
AS
BEGIN
	IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDN = @TENDN AND MATKHAU = @MK)
	BEGIN
		RETURN
	END

	SELECT MANV, HOTEN, EMAIL, LUONG FROM NHANVIEN WHERE TENDN = @TENDN
END

GO
CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_SINHVIEN
	@MASV VARCHAR(20),
    @HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MK VARBINARY(MAX)
AS
BEGIN
	INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI,MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MK);
END

GO
CREATE PROCEDURE SP_INS_ENCRYPT_DIEM_BY_SINHVIEN_AND_HOCPHAN
	@MASV VARCHAR(20),
    @MAHP VARCHAR(20),
    @DIEMTHI VARBINARY(MAX)
AS
BEGIN
	INSERT INTO BANGDIEM (MASV, MAHP, DIEMTHI)
    VALUES (@MASV, @MAHP, @DIEMTHI);
END

GO
CREATE PROCEDURE SP_UPDATE_ENCRYPT_DIEM_BY_SINHVIEN_AND_HOCPHAN
	@MASV VARCHAR(20),
    @MAHP VARCHAR(20),
    @DIEMTHI VARBINARY(MAX)
AS
BEGIN
	IF NOT EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = @MASV AND MAHP = @MAHP)
    BEGIN
        EXEC SP_INS_ENCRYPT_DIEM_BY_SINHVIEN_AND_HOCPHAN 
            @MASV,
            @MAHP,
            @DIEMTHI
        RETURN;
    END

	UPDATE BANGDIEM
    SET DIEMTHI = @DIEMTHI
    WHERE MASV = @MASV AND MAHP = @MAHP;
END
GO
CREATE PROCEDURE SP_SEL_PUBLIC_SINHVIEN_BY_NHANVIEN
	@MANV VARCHAR(20)
AS
BEGIN
	SELECT S.MASV, S.HOTEN, S.NGAYSINH, S.DIACHI, S.MALOP
	FROM SINHVIEN S
	JOIN LOP L ON L.MANV = @MANV AND L.MALOP = S.MALOP
END

GO
CREATE PROCEDURE SP_GET_ALL_ENCRYPT_HOCPHAN_WITH_DIEM_BY_SINHVIEN
	@MASV VARCHAR(20)
AS
BEGIN
	SELECT 
        H.MAHP,
        H.TENHP,
        H.SOTC,
        b.DIEMTHI
    FROM HOCPHAN H
    LEFT JOIN BANGDIEM B ON H.MAHP = B.MAHP AND B.MASV = @MASV
    ORDER BY H.MAHP;
END
GO
CREATE PROCEDURE SP_GET_ALL_LOP
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
        L.MALOP,
        L.TENLOP,
        L.MANV,
        N.HOTEN
    FROM LOP L
    LEFT JOIN NHANVIEN N ON L.MANV = N.MANV
    ORDER BY L.MALOP;
END;
GO
CREATE PROCEDURE SP_UPDATE_SINHVIEN
    @MASV VARCHAR(20),
    @HOTEN NVARCHAR(100) = NULL,
    @NGAYSINH DATETIME = NULL,
    @DIACHI NVARCHAR(200) = NULL
AS
BEGIN
    UPDATE SINHVIEN
    SET 
        HOTEN = ISNULL(@HOTEN, HOTEN),
        NGAYSINH = ISNULL(@NGAYSINH, NGAYSINH),
        DIACHI = ISNULL(@DIACHI, DIACHI)
    WHERE MASV = @MASV;
END;
GO
CREATE PROCEDURE SP_INS_LOP
    @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20)
AS
BEGIN
    INSERT INTO LOP (MALOP, TENLOP, MANV)
    VALUES (@MALOP, @TENLOP, @MANV);
END;
GO

CREATE PROCEDURE SP_INS_HOCPHAN
    @MAHP VARCHAR(20),
    @TENHP NVARCHAR(100),
    @SOTC INT = 3 -- Giá trị mặc định
AS
BEGIN
    INSERT INTO HOCPHAN (MAHP, TENHP, SOTC)
    VALUES (@MAHP, @TENHP, @SOTC);
END;
--select * from nhanvien
/*
	select * from lop

	delete from nhanvien where manv = 'NV001'
	delete from nhanvien where manv = 'NV002'
*/