USE QLSVNhom

GO
	SELECT * FROM SYS.procedures
GO
/* 
	DROP PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
	DROP PROCEDURE SP_SIGN_IN_ENCRYPT_NHANVIEN
	DROP PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
*/
GO

CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG VARBINARY(MAX),
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX),
	@PUB VARCHAR(20)
AS
BEGIN
	INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
	VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @MANV)
END

GO

CREATE PROCEDURE SP_SIGN_IN_ENCRYPT_NHANVIEN
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX)
AS
BEGIN
	IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDN = @TENDN AND MATKHAU = @MK)
	BEGIN
		SELECT 0
		RETURN
	END

	SELECT 1
	RETURN
END

GO

CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX)
AS
BEGIN
	IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDN = @TENDN AND MATKHAU = @MK)
	BEGIN
		RETURN
	END

	SELECT MANV, HOTEN, EMAIL, LUONG FROM NHANVIEN WHERE TENDN = @TENDN
END

select * from nhanvien

delete from nhanvien where manv = 'NV001'
delete from nhanvien where manv = 'NV002'