server:
  port: 8080
  servlet:
    context-path: /student

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433
    username: sa            
    password: your_password     
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  cloud:
    config:
      import-check:
        enabled: false

