server:
  port: 8080
app:
  datasource:
    sqlserver:
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=QLSVNhom;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8
      username: sa
      password: abcd
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    sqlite:
      jdbc-url: jdbc:sqlite:src/main/resources/key.db
      driver-class-name: org.sqlite.JDBC
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
